name: BuildWindows

on:
  push:
    branches:
      - actions-test
  release:
    types: [published, edited, prereleased]
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1

    - name: Install Crystal
      uses: oprypin/install-crystal@v1
      with:
        crystal: nightly
        
    - name: Set up environment
      run: |
        echo "CRYSTAL_PATH=$(pwd)\..;${env:CRYSTAL_PATH}" >>${env:GITHUB_ENV}
    
    - name: Build
      run: |
        rake
        
    - name: Run
      run: |
        build/launshi/bin/Launshi.exe --version
      
    - name: Install7z
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
      
    - name: Zip
      run: |
        7z a Launshi_win_x64.zip -r build/launshi/bin/*
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Launshi
        path: Launshi_win_x64.zip
        
