name: BuildWindows

on:
  push:
    branches: [master]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v1.1
    - uses: seanmiddleditch/gha-setup-vsdevenv@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
        crystal: nightly
        
    - name: Deps
      run: |
        git submodule init
        git submodule update --recursive
        tree third_party /A /F
    
    - name: Build
      run: |
        rake -v
        tree build/launshi /A /F
        
    - name: Run
      run: |
        build/launshi/bin/Launshi.exe --version
      
    - name: Install7z
      shell: powershell
      run: Install-Module 7Zip4PowerShell -Force -Verbose
      
    - name: Zip
      run: |
        7z a Launshi_win_x64.zip -r build/launshi/bin/*
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Launshi
        path: Launshi_win_x64.zip
        
